---
deployment:
  tasks:
    - export PATH=$HOME/bin:$HOME/nodevenv/weraw/app/22/bin:$PATH
    - cd /home/uqkn2942/weraw
    - pnpm install 
    - pnpm run build -P
    - cd ./build
    - pnpm install --prod
    - echo "Déploiement terminé avec succès !"
