name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.15.6
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Update npm to latest version
        run: npm install -g npm@latest

      - name: Install dependencies
        run: pnpm install
        working-directory: ./app

      - name: Install dependencies
        run: pnpm build
        working-directory: ./app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            nvm use 22
            cd ~/htdocs/www.weraw.fr
            npm install -g npm@latest
            git pull origin main
            cd app
            pnpm install
            pnpm build
            cd build

            # Create .env file
            cat > .env << 'EOL'
            NODE_ENV=production
            ${{ secrets.ENV_CONTENT }}
            EOL

            pnpm i -P
            node ace migration:run --force
            pm2 restart bin/server.js
